artifact_location: file:C:/Users/gcass/OneDrive/Bureau/ML_Projects/purchase-predict/MLFLOW_SERVER/0
creation_time: 1769968703339
experiment_id: '0'
last_update_time: 1769968703339
lifecycle_stage: active
name: Default
