test_ratio: 0.3
auto_ml_max_evals: 1
gcp_project_id: "mlops-485718" 
gcs_primary_folder: "purchase-predict-blent/purchase"
mlflow_enabled: True
mlflow_experiment_id: "1"
mlflow_model_registry: "purchase_predict"
